Repository hassio-addons/addon-vscode, pull requests merged in 2021-03, with the labels that each got.

#191 ⬆️ Upgrades esbenp.prettier-vscode to 5.9.2
  vscode/vscode.extensions
Labels: dependencies

#193 :arrow_up: Upgrades add-on base image to v4.1.3
  vscode/Dockerfile
  vscode/build.json
Labels: dependencies

#195 :arrow_up: Upgrades emilast.LogFileHighlighter to 2.11.0
  vscode/vscode.extensions
Labels: dependencies

#196 :arrow_up: Upgrades redhat.vscode-yaml to 0.16.0
  vscode/vscode.extensions
Labels: dependencies

#194 :arrow_up: Upgrades code-server to 3.9.1
  vscode/Dockerfile
Labels: dependencies

#198 ⬆️ Upgrades Home Assistant CLI to v4.11.0
  vscode/Dockerfile
Labels: dependencies

#205 ⬆️ Upgrades esbenp.prettier-vscode to 6.3.1
  vscode/vscode.extensions
Labels: dependencies

#206 ⬆️ Upgrades usernamehw.errorlens to 3.2.5
  vscode/vscode.extensions
Labels: dependencies

#204 ⬆️ Upgrades Home Assistant CLI to v4.11.2
  vscode/Dockerfile
Labels: dependencies

#207 ⬆️ Upgrades ESPHome.esphome-vscode to 0.13.0
  vscode/vscode.extensions
Labels: dependencies

#209 ⬆️ Upgrades keesschollaart.vscode-home-assistant to 1.15.0
  vscode/vscode.extensions
Labels: dependencies

#197 Common directories in /root like SSH add-on
  vscode/DOCS.md
  vscode/rootfs/etc/cont-init.d/user.sh
Labels: new-feature

#211 Assign ESPHome files to the ESPHome extension
  vscode/rootfs/etc/cont-init.d/code-server.sh
  vscode/rootfs/root/.code-server/settings.json
Labels: enhancement

#213 ⬆️ Upgrades Home Assistant CLI to v4.11.3
  vscode/Dockerfile
Labels: dependencies
