Repository hassio-addons/addon-vscode, pull requests merged in 2022-06, with the labels that each got.

#462 ⬆️ Upgrades Home Assistant CLI to v4.18.0
  vscode/Dockerfile
Labels: dependencies

#463 ⬆️ Upgrades keesschollaart.vscode-home-assistant to 1.30.1
  vscode/vscode.extensions
Labels: dependencies

#464 :books: Documentation cleanup
  vscode/DOCS.md
Labels: documentation

#467 ⬆️ Upgrades emilast.LogFileHighlighter to 2.16.0
  vscode/vscode.extensions
Labels: dependencies

#471 ⬆️ Upgrades ESPHome.esphome-vscode to 2022.6.1
  vscode/vscode.extensions
Labels: dependencies

#469 Add `less` command
  vscode/Dockerfile
Labels: enhancement
