Repository hassio-addons/addon-vscode, pull requests merged in 2022-03, with the labels that each got.

#394 Fix typo
  vscode/DOCS.md
Labels: documentation

#404 :ambulance: Use https instead of git protocol to fetch sources
  vscode/Dockerfile
Labels: maintenance

#403 ⬆️ Upgrades add-on base image to 5.3.0
  vscode/Dockerfile
  vscode/build.yaml
Labels: dependencies

#405 :lock: Sign add-on with Codenotary Community Attestation Service (CAS)
  .github/workflows/deploy.yaml
  vscode/build.yaml
  vscode/config.yaml
Labels: enhancement

#406 ⬆️ Upgrades code-server to 4.2.0
  vscode/Dockerfile
Labels: dependencies

#407 ⬆️ Upgrades emilast.LogFileHighlighter to 2.15.0
  vscode/vscode.extensions
Labels: dependencies

#408 ⬆️ Upgrades netcorext.uuid-generator to 0.0.5
  vscode/vscode.extensions
Labels: dependencies

#409 ⬆️ Upgrades esbenp.prettier-vscode to 9.3.0
  vscode/vscode.extensions
Labels: dependencies

#410 ⬆️ Upgrades usernamehw.errorlens to 3.4.2
  vscode/vscode.extensions
Labels: dependencies

#411 ⬆️ Upgrades redhat.vscode-yaml to 1.5.1
  vscode/vscode.extensions
Labels: dependencies

#412 :ambulance: Fix build-in extensions path
  vscode/Dockerfile
Labels: bugfix
