Repository hassio-addons/addon-vscode, pull requests merged in 2023-03, with the labels that each got.

#581 ⬆️ Upgrades add-on base image to 6.2.3
  vscode/Dockerfile
  vscode/build.yaml
Labels: dependencies

#580 Use shim instead of symlink for code CLI
  vscode/Dockerfile
  vscode/rootfs/usr/local/bin/code
Labels: enhancement

#582 ⬆️ Upgrades code-server to 4.10.1
  vscode/Dockerfile
Labels: dependencies

#583 ⬆️ Upgrades keesschollaart.vscode-home-assistant to 1.34.0
  vscode/vscode.extensions
Labels: dependencies

#588 ⬆️ Upgrades code-server to 4.11.0
  vscode/Dockerfile
Labels: dependencies

#593 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  vscode/Dockerfile
Labels: maintenance

#602 Update URLs in documentation
  vscode/DOCS.md
Labels: documentation

#603 :hammer: Adjust upstream code-server org name
  .github/renovate.json
  vscode/Dockerfile
Labels: maintenance
