Repository hassio-addons/addon-vscode, pull requests merged in 2025-02, with the labels that each got.

#924 :fireworks: Updates maintenance/license year to 2025
  LICENSE.md
  README.md
  vscode/.README.j2
  vscode/DOCS.md
Labels: maintenance

#922 init-user: Safeguarded linking directories and files
  vscode/rootfs/etc/s6-overlay/s6-rc.d/init-user/run
Labels: enhancement

#930 Revert "⬆️ Update cdr/code-server to v4.97.2 (#927)"
  vscode/Dockerfile
Labels: dependencies
